spring.datasource.url=jdbc:postgresql://localhost:5432/eventsphere
spring.datasource.username=suyashgupta
spring.datasource.password=123456789
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

app.jwt.secret=4cbc3cd0ddd4404d5dbbafab8f8e36bbd449e84ead942f799f0da8d0fde3cdbf
app.jwt.expiration=3600000

logging.level.org.hibernate.SQL=INFO
logging.level.com.eventsphere=INFO
